import type { Octokit } from "@octokit/core";

interface CreatePullRequestParams {
  octokit: Octokit;
  owner: string;
  repo: string;
  head: string;
  base: string;
  title: string;
  body: string;
  reviewer: string;
}

interface PullRequestResult {
  prNumber: number;
  prUrl: string;
}

export async function createPullRequest(
  params: CreatePullRequestParams,
): Promise<PullRequestResult> {
  const { octokit, owner, repo, head, base, title, body, reviewer } = params;

  const { data: pr } = await octokit.request(
    "POST /repos/{owner}/{repo}/pulls",
    { owner, repo, head, base, title, body },
  );

  try {
    await octokit.request(
      "POST /repos/{owner}/{repo}/pulls/{pull_number}/requested_reviewers",
      { owner, repo, pull_number: pr.number, reviewers: [reviewer] },
    );
  } catch {
    // Fails if sender is repo owner — that's fine
  }

  return { prNumber: pr.number, prUrl: pr.html_url };
}

export function buildPRTitle(issueTitle: string, issueNumber: number): string {
  const suffix = ` (#${issueNumber})`;
  const maxTitleLength = 70 - suffix.length;

  if (issueTitle.length > maxTitleLength) {
    return issueTitle.slice(0, maxTitleLength - 3) + "..." + suffix;
  }

  return issueTitle + suffix;
}

export function buildPRBody(
  issueNumber: number,
  agentOutput: string,
): string {
  const truncatedOutput =
    agentOutput.length > 5000
      ? agentOutput.slice(0, 5000) + "\n\n_(output truncated)_"
      : agentOutput;

  return `Closes #${issueNumber}

## Summary

${truncatedOutput}

---
_Generated by [mollusk](https://github.com/mollusk) 🐚_`;
}
